name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Inject API Key into HTML
        run: |
          sed -i '/<head>/a \    <script>window.GOOGLE_BOOKS_API_KEY = "${{ secrets.GOOGLE_BOOKS_API_KEY }}";</script>' index.html
          sed -i '/<head>/a \    <script>window.GOOGLE_BOOKS_API_KEY = "${{ secrets.GOOGLE_BOOKS_API_KEY }}";</script>' book.html
          sed -i '/<head>/a \    <script>window.GOOGLE_BOOKS_API_KEY = "${{ secrets.GOOGLE_BOOKS_API_KEY }}";</script>' myBooks.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
          enable_jekyll: false
